package com.abdeveloper.abscanner.codec

object Gs1PrefixDirectory {

    fun lookupCountryOrCategory(code: String): String? {
        val clean = code.trim().filter { it.isDigit() }
        if (clean.length < 3) return null

        val prefix3 = clean.substring(0, 3).toIntOrNull() ?: return null

        if (prefix3 in 0..19 || prefix3 in 30..39 || prefix3 in 60..139) return "GS1 US / Canada"
        if (prefix3 in 200..299) return "Restricted distribution (internal store use)"
        if (prefix3 in 300..379) return "GS1 France"
        if (prefix3 == 380) return "GS1 Bulgaria"
        if (prefix3 == 383) return "GS1 Slovenia"
        if (prefix3 == 385) return "GS1 Croatia"
        if (prefix3 in 400..440) return "GS1 Germany"
        if (prefix3 in 450..459 || prefix3 in 490..499) return "GS1 Japan"
        if (prefix3 in 460..469) return "GS1 Russia"
        if (prefix3 == 471) return "GS1 Taiwan"
        if (prefix3 == 474) return "GS1 Estonia"
        if (prefix3 == 480) return "GS1 Philippines"
        if (prefix3 == 489) return "GS1 Hong Kong"
        if (prefix3 in 500..509) return "GS1 United Kingdom"
        if (prefix3 in 520..521) return "GS1 Greece"
        if (prefix3 == 528) return "GS1 Lebanon"
        if (prefix3 == 529) return "GS1 Cyprus"
        if (prefix3 in 535..539) return "GS1 Ireland & Malta"
        if (prefix3 in 540..549) return "GS1 Belgium & Luxembourg"
        if (prefix3 == 560) return "GS1 Portugal"
        if (prefix3 == 569) return "GS1 Iceland"
        if (prefix3 in 570..579) return "GS1 Denmark"
        if (prefix3 in 590..599) return "GS1 Poland & Central Europe"
        if (prefix3 in 600..601) return "GS1 South Africa"
        if (prefix3 == 608) return "GS1 Bahrain"
        if (prefix3 == 609) return "GS1 Mauritius"
        if (prefix3 == 611) return "GS1 Morocco"
        if (prefix3 == 613) return "GS1 Algeria"
        if (prefix3 == 616) return "GS1 Kenya"
        if (prefix3 == 619) return "GS1 Tunisia"
        if (prefix3 == 621) return "GS1 Syria"
        if (prefix3 == 622) return "GS1 Egypt"
        if (prefix3 == 624) return "GS1 Libya"
        if (prefix3 == 625) return "GS1 Jordan"
        if (prefix3 == 626) return "GS1 Iran"
        if (prefix3 == 627) return "GS1 Kuwait"
        if (prefix3 == 628) return "GS1 Saudi Arabia"
        if (prefix3 == 629) return "GS1 United Arab Emirates"
        if (prefix3 in 640..649) return "GS1 Finland"
        if (prefix3 in 690..699) return "GS1 China"
        if (prefix3 in 700..709) return "GS1 Norway"
        if (prefix3 == 729) return "GS1 Israel"
        if (prefix3 in 730..739) return "GS1 Sweden"
        if (prefix3 == 740) return "GS1 Guatemala"
        if (prefix3 == 741) return "GS1 El Salvador"
        if (prefix3 == 742) return "GS1 Honduras"
        if (prefix3 == 743) return "GS1 Nicaragua"
        if (prefix3 == 744) return "GS1 Costa Rica"
        if (prefix3 == 745) return "GS1 Panama"
        if (prefix3 in 750..759) return "GS1 Mexico, Venezuela"
        if (prefix3 in 760..769) return "GS1 Switzerland / Liechtenstein"
        if (prefix3 == 770) return "GS1 Colombia"
        if (prefix3 == 773) return "GS1 Uruguay"
        if (prefix3 == 775) return "GS1 Peru"
        if (prefix3 == 777) return "GS1 Bolivia"
        if (prefix3 == 779) return "GS1 Argentina"
        if (prefix3 == 780) return "GS1 Chile"
        if (prefix3 == 784) return "GS1 Paraguay"
        if (prefix3 == 786) return "GS1 Ecuador"
        if (prefix3 in 789..790) return "GS1 Brazil"
        if (prefix3 in 800..839) return "GS1 Italy"
        if (prefix3 in 840..849) return "GS1 Spain"
        if (prefix3 == 850) return "GS1 Cuba"
        if (prefix3 == 858) return "GS1 Slovakia"
        if (prefix3 == 859) return "GS1 Czech Republic"
        if (prefix3 == 860) return "GS1 Serbia"
        if (prefix3 in 868..869) return "GS1 Turkey"
        if (prefix3 in 870..879) return "GS1 Netherlands"
        if (prefix3 == 880) return "GS1 South Korea"
        if (prefix3 == 884) return "GS1 Cambodia"
        if (prefix3 == 885) return "GS1 Thailand"
        if (prefix3 == 888) return "GS1 Singapore"
        if (prefix3 == 890) return "GS1 India"
        if (prefix3 == 893) return "GS1 Vietnam"
        if (prefix3 == 896) return "GS1 Pakistan"
        if (prefix3 == 899) return "GS1 Indonesia"
        if (prefix3 in 900..919) return "GS1 Austria"
        if (prefix3 in 930..939) return "GS1 Australia"
        if (prefix3 in 940..949) return "GS1 New Zealand"
        if (prefix3 == 955) return "GS1 Malaysia"
        if (prefix3 == 958) return "GS1 Macau"
        if (prefix3 == 977) return "Serial Publications (ISSN)"
        if (prefix3 == 978 || prefix3 == 979) return "Bookland (ISBN)"
        if (prefix3 in 981..984) return "Common Currency Coupons"
        if (prefix3 in 990..999) return "Coupons / Vouchers"

        return null
    }

    fun lookupGs1ApplicationIdentifier(ai: String): String? {
        return when (ai) {
            "00" -> "SSCC (Serial Shipping Container Code)"
            "01" -> "GTIN (Global Trade Item Number)"
            "02" -> "Content GTIN"
            "10" -> "Batch / Lot Number"
            "11" -> "Production Date (YYMMDD)"
            "12" -> "Due Date (YYMMDD)"
            "13" -> "Packaging Date (YYMMDD)"
            "15" -> "Best Before Date (YYMMDD)"
            "17" -> "Expiration Date (YYMMDD)"
            "20" -> "Internal Product Variant"
            "21" -> "Serial Number"
            "30" -> "Variable Count"
            "310" -> "Net Weight (kg)"
            "37" -> "Number of Units Contained"
            "400" -> "Customer Purchase Order Number"
            "410" -> "Ship to / Deliver to Location"
            "420" -> "Ship to Postal Code"
            "421" -> "Ship to Country and Postal Code"
            "8005" -> "Price per Unit of Measure"
            else -> null
        }
    }
}
